Loosen the domain regex to accept '.'
ruby/cgi pull request #29
Opened 2022-11-22 10:13 UTC by tubaxenor

Domain leading with `.` should be allowed since it represents all subdomain are sharing the same cookie.

2022-11-22 10:14 UTC, tubaxenor commented
Seems like the leading dot is old standard according to the discussion here: https://stackoverflow.com/a/23086139
But I think this lib should still support this instead of treating it as invalid value.

2022-11-22 14:19 UTC, tubaxenor commented
Looks like I did the regex wrong, @nobu @hsbt any chance I can get some help here?

2022-11-22 15:27 UTC, casperisfine commented on lib/cgi/cookie.rb
> +    DOMAIN_VALUE_RE = %r"\A(?<label>(?!-)[-A-Za-z0-9.]+(?<!-))(?:\.\g<label>)*\z"
```suggestion
    DOMAIN_VALUE_RE = %r"\A(?<label>(?!-)\.?[-A-Za-z0-9]+(?<!-))(?:\.\g<label>)*\z"
```
This should do ^

2022-11-23 08:05 UTC, casperisfine commented
LGTM, but you probably want to squash these commits and to remove that blank line in the diff.

2022-11-23 09:32 UTC, casperisfine commented
The CI failures are already on master.

2022-11-24 02:02 UTC, mame commented
This is a consequence of our decision to comply with RFC 6265.

https://www.rfc-editor.org/rfc/rfc6265#section-4.1.1

```
 domain-value      = <subdomain>
                       ; defined in [RFC1034], Section 3.5, as
                       ; enhanced by [RFC1123], Section 2.1
```

It looks like the referenced RFCs do not allow a leading dot.

https://www.rfc-editor.org/rfc/rfc1034#section-3.5
https://www.rfc-editor.org/rfc/rfc1123#section-2

However, a leading dot was *required* in RFC 2109 (which has been already obsoleted).

https://datatracker.ietf.org/doc/html/rfc2109#section-4.2.2

```
   Domain=domain
      Optional.  The Domain attribute specifies the domain for which the
      cookie is valid.  An explicitly specified domain must always start
      with a dot.
```

We may allow leading dots for compatibility. @akr @nurse What do you think?

2022-11-24 14:27 UTC, nobu requested changes

2022-11-24 14:27 UTC, nobu commented on lib/cgi/cookie.rb
> +    DOMAIN_VALUE_RE = %r"\A(?<label>(?!-)\.?[-A-Za-z0-9]+(?<!-))(?:\.\g<label>)*\z"
This accepts "example..com" too.
```suggestion
    DOMAIN_VALUE_RE = %r"\A\.?(?<label>(?!-)[-A-Za-z0-9]+(?<!-))(?:\.\g<label>)*\z"
```

2022-11-25 06:24 UTC, kylesnowschwartz commented
Hi all, we are encountering this problem on my project when trying to update to the patched version of Ruby 2.7.7. Our test builds are failing due to the leading . on our cookie domains. This is a Rails project version 2.6.7. It would be great to have this PR out so that we can patch up this security flaw as soon as possible.

2022-11-25 07:43 UTC, casperisfine commented
I just noticed that this is breaking Rails test suite as well: https://buildkite.com/rails/rails/builds/91200#0184aae9-a971-4423-8bb6-60e7a14ec3fb/1048-1057

2022-11-25 07:45 UTC, nobu approved these changes

2022-11-25 10:54 UTC, kenvatian commented
Thank you for your work, and for picking up this issue so quickly.

My 2 cents: I think, sticking with [RFC6265 Section 4.1.1](https://www.rfc-editor.org/rfc/rfc6265#section-4.1.1) is the future. To get there, maybe a version is released to deprecate the leading dot and allow various frameworks a grace period to remove support of the leading dot. Then release another version that raises an exception for the leading dot. Thanks.

P.S. As per https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#domaindomain-value, it's odd that frameworks are still producing domain value with leading dot, because 

> ...if a domain is specified, then subdomains are always included.

2022-11-28 03:27 UTC, mame commented
@naruse found the following statements in RFC 6265

> [5.2.3](https://www.rfc-editor.org/rfc/rfc6265#section-5.2.3).  The Domain Attribute
>
> *snip*
>
> If the first character of the attribute-value string is %x2E ("."):
>
>   Let cookie-domain be the attribute-value without the leading %x2E
>   (".") character.

So it looks like RFC 6265 actually allows a leading dot. I no longer see any reason not to merge this PR.

2022-11-28 04:34 UTC, merged

2022-12-13 00:40 UTC, taketo1113 commented
Any plans to backport this PR to v0.2.x (for ruby 3.0.x) and v0.1.x (for ruby 2.7.x)?

If no backport, it seems to need updating cgi gem per release of ruby 3.0.5+.

2023-04-23 17:29 UTC, gareth commented
> So it looks like RFC 6265 actually allows a leading dot. I no longer see any reason not to merge this PR.

This is true but slightly misleading. RFC6265 doesn't strictly *allow* a leading dot (it actually defines the domain parameter as _not permitting_ a leading dot), but it gives a fallback behaviour for UAs to be able to handle older RFC2965 cookies.

The difference is important because there is discussion pointing to this PR as justification for keeping leading dots on cookies in Rails.

In fact, there's an argument that maybe this PR didn't go far enough? As you quoted, the RFC6265 behaviour is this:

> Let cookie-domain be the attribute-value without the leading %x2E (".") character.

However the library persists the leading dot:

```
$ pry -r cgi
[1] pry(main)> cookie = CGI::Cookie.new "name" => "foo", "domain" => ".example.com"
=> []
[2] pry(main)> cookie.domain
=> ".example.com"
```

This PR was enough to stop exceptions being raised for cookies that browsers would handle though, and that's clearly a good thing regardless of the extra details.